apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: basic-nodejs-cert
  namespace: default
spec:
  secretName: basic-nodejs-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: trickshotrodeo.com
  dnsNames:
  - "*.trickshotrodeo.com"
  - trickshotrodeo.com