apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: basic-nodejs-cert
  namespace: basic-nodejs
spec:
  secretName: basic-nodejs-tls
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: trickshotrodeo.com
  dnsNames:
  - "*.trickshotrodeo.com"
  - trickshotrodeo.com