apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-nodejs-ingress
  namespace: basic-nodejs
spec:
  rules:
  - host: basicnodejs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: basic-nodejs-service
            port:
              number: 3200