apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-nodejs-ingress
  namespace: basic-nodejs
spec:
  backend:
    serviceName: basic-nodejs-service
    servicePort: 3200
  rules:
  - host: trickshotrodeo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: basic-nodejs-service
          servicePort: 3200