apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: basic-nodejs
spec:
  acme:
    email: alexa.sparks@wpengine.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        clouddns:
          project: testing-project-local-team
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-account
            key: key.json